# Generated by Django 4.2.3 on 2024-04-24 08:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Введите содержание для объекта.', verbose_name='Содержание')),
                ('content_ru', models.TextField(help_text='Введите содержание для объекта.', null=True, verbose_name='Содержание')),
                ('content_en', models.TextField(help_text='Введите содержание для объекта.', null=True, verbose_name='Содержание')),
                ('content_uz', models.TextField(help_text='Введите содержание для объекта.', null=True, verbose_name='Содержание')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас (множественное число)',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Title of the blog post', max_length=200, verbose_name='Title')),
                ('title_ru', models.CharField(help_text='Title of the blog post', max_length=200, null=True, verbose_name='Title')),
                ('title_en', models.CharField(help_text='Title of the blog post', max_length=200, null=True, verbose_name='Title')),
                ('title_uz', models.CharField(help_text='Title of the blog post', max_length=200, null=True, verbose_name='Title')),
                ('description', models.TextField(help_text='Brief description of the blog post', verbose_name='Description')),
                ('description_ru', models.TextField(help_text='Brief description of the blog post', null=True, verbose_name='Description')),
                ('description_en', models.TextField(help_text='Brief description of the blog post', null=True, verbose_name='Description')),
                ('description_uz', models.TextField(help_text='Brief description of the blog post', null=True, verbose_name='Description')),
                ('country', models.CharField(blank=True, help_text='Country of the blog post', max_length=255, null=True, verbose_name='Country')),
                ('country_ru', models.CharField(blank=True, help_text='Country of the blog post', max_length=255, null=True, verbose_name='Country')),
                ('country_en', models.CharField(blank=True, help_text='Country of the blog post', max_length=255, null=True, verbose_name='Country')),
                ('country_uz', models.CharField(blank=True, help_text='Country of the blog post', max_length=255, null=True, verbose_name='Country')),
                ('address', models.TextField(blank=True, help_text='Address of the blog post', null=True, verbose_name='Address')),
                ('address_ru', models.TextField(blank=True, help_text='Address of the blog post', null=True, verbose_name='Address')),
                ('address_en', models.TextField(blank=True, help_text='Address of the blog post', null=True, verbose_name='Address')),
                ('address_uz', models.TextField(blank=True, help_text='Address of the blog post', null=True, verbose_name='Address')),
                ('contact_information', models.TextField(blank=True, help_text='Contact information for the blog post', null=True, verbose_name='Contact Information')),
                ('contact_information_ru', models.TextField(blank=True, help_text='Contact information for the blog post', null=True, verbose_name='Contact Information')),
                ('contact_information_en', models.TextField(blank=True, help_text='Contact information for the blog post', null=True, verbose_name='Contact Information')),
                ('contact_information_uz', models.TextField(blank=True, help_text='Contact information for the blog post', null=True, verbose_name='Contact Information')),
                ('slug', models.SlugField(blank=True, help_text='Slug for the URL of the blog post. Automatically generated from the title.', max_length=200, unique=True, verbose_name='Slug')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='View Count')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('country', models.CharField(help_text='Country of the contact address', max_length=255, verbose_name='Country')),
                ('city', models.CharField(help_text='City of the contact address', max_length=255, verbose_name='City')),
                ('address', models.CharField(help_text='Contact address including postal code', max_length=500, verbose_name='Address')),
                ('phone_number', models.CharField(help_text='Phone number including country and city code', max_length=255, verbose_name='Phone Number')),
                ('email', models.EmailField(help_text='Email address for communication', max_length=254, verbose_name='Email')),
                ('landmark', models.CharField(help_text='Nearest landmark to help locate the address', max_length=200, verbose_name='Landmark')),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Latitude coordinate of the location', max_digits=9, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Longitude coordinate of the location', max_digits=9, verbose_name='Longitude')),
            ],
            options={
                'verbose_name_plural': 'Contact Information',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Введите ваш номер телефона.', max_length=20, verbose_name='Номер телефона')),
                ('title', models.CharField(help_text='Введите заголовок.', max_length=255, verbose_name='Заголовок')),
                ('index_code', models.CharField(help_text='Введите индекс.', max_length=20, verbose_name='Индекс')),
                ('name', models.CharField(help_text='Введите ваше имя.', max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(help_text='Введите вашу фамилию.', max_length=100, verbose_name='Фамилия')),
                ('address', models.TextField(help_text='Введите ваш адрес.', max_length=255, verbose_name='Адрес')),
                ('note', models.TextField(help_text='Введите любые дополнительные заметки.', verbose_name='Заметка')),
                ('description', models.TextField(help_text='Напишите описание отзыва о данной услуге.', verbose_name='Описание')),
                ('mail', models.EmailField(help_text='Введите ваш адрес электронной почты.', max_length=255, verbose_name='Электронная почта')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Заголовок услуги', max_length=200, verbose_name='Заголовок')),
                ('title_ru', models.CharField(help_text='Заголовок услуги', max_length=200, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(help_text='Заголовок услуги', max_length=200, null=True, verbose_name='Заголовок')),
                ('title_uz', models.CharField(help_text='Заголовок услуги', max_length=200, null=True, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, help_text='URL-часть для заголовка. Автоматически генерируется.', max_length=200, unique=True, verbose_name='URL-часть')),
                ('descriptions', models.TextField(help_text='Описания услуги', verbose_name='Описания')),
                ('descriptions_ru', models.TextField(help_text='Описания услуги', null=True, verbose_name='Описания')),
                ('descriptions_en', models.TextField(help_text='Описания услуги', null=True, verbose_name='Описания')),
                ('descriptions_uz', models.TextField(help_text='Описания услуги', null=True, verbose_name='Описания')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Image associated with the service', upload_to='service_images/', verbose_name='Image')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_service', to='projects.service')),
            ],
        ),
        migrations.CreateModel(
            name='Review_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='review_images/', verbose_name='Imagereview')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_review', to='projects.review')),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='service',
            field=models.ForeignKey(help_text='Укажите услугу, к которой относится этот отзыв.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='projects.service', verbose_name='Услуга'),
        ),
        migrations.CreateModel(
            name='Blog_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog_images/', verbose_name='Imageblog')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_blog', to='projects.blog')),
            ],
        ),
        migrations.CreateModel(
            name='About_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about_images/', verbose_name='Imageabout')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_about', to='projects.about')),
            ],
        ),
    ]
