# Generated by Django 4.2.3 on 2024-04-24 05:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите заголовок для объекта.', max_length=200, verbose_name='Заголовок')),
                ('title_ru', models.CharField(help_text='Введите заголовок для объекта.', max_length=200, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(help_text='Введите заголовок для объекта.', max_length=200, null=True, verbose_name='Заголовок')),
                ('title_uz', models.CharField(help_text='Введите заголовок для объекта.', max_length=200, null=True, verbose_name='Заголовок')),
                ('content', models.TextField(help_text='Введите содержание для объекта.', verbose_name='Содержание')),
                ('content_ru', models.TextField(help_text='Введите содержание для объекта.', null=True, verbose_name='Содержание')),
                ('content_en', models.TextField(help_text='Введите содержание для объекта.', null=True, verbose_name='Содержание')),
                ('content_uz', models.TextField(help_text='Введите содержание для объекта.', null=True, verbose_name='Содержание')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания объекта будут автоматически заполнены.', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата и время обновления объекта будут автоматически обновляться при сохранении.', verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас (множественное число)',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Title of the blog post', max_length=200, verbose_name='Title')),
                ('title_ru', models.CharField(help_text='Title of the blog post', max_length=200, null=True, verbose_name='Title')),
                ('title_en', models.CharField(help_text='Title of the blog post', max_length=200, null=True, verbose_name='Title')),
                ('title_uz', models.CharField(help_text='Title of the blog post', max_length=200, null=True, verbose_name='Title')),
                ('description', models.TextField(help_text='Brief description of the blog post', verbose_name='Description')),
                ('description_ru', models.TextField(help_text='Brief description of the blog post', null=True, verbose_name='Description')),
                ('description_en', models.TextField(help_text='Brief description of the blog post', null=True, verbose_name='Description')),
                ('description_uz', models.TextField(help_text='Brief description of the blog post', null=True, verbose_name='Description')),
                ('country', models.CharField(blank=True, help_text='Country of the blog post', max_length=255, null=True, verbose_name='Country')),
                ('country_ru', models.CharField(blank=True, help_text='Country of the blog post', max_length=255, null=True, verbose_name='Country')),
                ('country_en', models.CharField(blank=True, help_text='Country of the blog post', max_length=255, null=True, verbose_name='Country')),
                ('country_uz', models.CharField(blank=True, help_text='Country of the blog post', max_length=255, null=True, verbose_name='Country')),
                ('address', models.TextField(blank=True, help_text='Address of the blog post', null=True, verbose_name='Address')),
                ('address_ru', models.TextField(blank=True, help_text='Address of the blog post', null=True, verbose_name='Address')),
                ('address_en', models.TextField(blank=True, help_text='Address of the blog post', null=True, verbose_name='Address')),
                ('address_uz', models.TextField(blank=True, help_text='Address of the blog post', null=True, verbose_name='Address')),
                ('contact_information', models.TextField(blank=True, help_text='Contact information for the blog post', null=True, verbose_name='Contact Information')),
                ('contact_information_ru', models.TextField(blank=True, help_text='Contact information for the blog post', null=True, verbose_name='Contact Information')),
                ('contact_information_en', models.TextField(blank=True, help_text='Contact information for the blog post', null=True, verbose_name='Contact Information')),
                ('contact_information_uz', models.TextField(blank=True, help_text='Contact information for the blog post', null=True, verbose_name='Contact Information')),
                ('slug', models.SlugField(blank=True, help_text='Slug for the URL of the blog post. Automatically generated from the title.', max_length=200, unique=True, verbose_name='Slug')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='View Count')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('country', models.CharField(help_text='Country of the contact address', max_length=255, verbose_name='Country')),
                ('city', models.CharField(help_text='City of the contact address', max_length=255, verbose_name='City')),
                ('address', models.CharField(help_text='Contact address including postal code', max_length=500, verbose_name='Address')),
                ('phone_number', models.CharField(help_text='Phone number including country and city code', max_length=255, verbose_name='Phone Number')),
                ('email', models.EmailField(help_text='Email address for communication', max_length=254, verbose_name='Email')),
                ('landmark', models.CharField(help_text='Nearest landmark to help locate the address', max_length=200, verbose_name='Landmark')),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Latitude coordinate of the location', max_digits=9, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Longitude coordinate of the location', max_digits=9, verbose_name='Longitude')),
            ],
            options={
                'verbose_name_plural': 'Contact Information',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Заголовок услуги', max_length=200, verbose_name='Заголовок')),
                ('title_ru', models.CharField(help_text='Заголовок услуги', max_length=200, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(help_text='Заголовок услуги', max_length=200, null=True, verbose_name='Заголовок')),
                ('title_uz', models.CharField(help_text='Заголовок услуги', max_length=200, null=True, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, help_text='URL-часть для заголовка. Автоматически генерируется.', max_length=200, unique=True, verbose_name='URL-часть')),
                ('image', models.ImageField(blank=True, help_text='Загрузите фотографию участника Услуга.', null=True, upload_to='service_images/', verbose_name='Фотография')),
                ('descriptions', models.TextField(help_text='Описания услуги', verbose_name='Описания')),
                ('descriptions_ru', models.TextField(help_text='Описания услуги', null=True, verbose_name='Описания')),
                ('descriptions_en', models.TextField(help_text='Описания услуги', null=True, verbose_name='Описания')),
                ('descriptions_uz', models.TextField(help_text='Описания услуги', null=True, verbose_name='Описания')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров.')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(help_text='Укажите ваше полное имя.', max_length=50, verbose_name='Полное имя')),
                ('full_name_ru', models.CharField(help_text='Укажите ваше полное имя.', max_length=50, null=True, verbose_name='Полное имя')),
                ('full_name_en', models.CharField(help_text='Укажите ваше полное имя.', max_length=50, null=True, verbose_name='Полное имя')),
                ('full_name_uz', models.CharField(help_text='Укажите ваше полное имя.', max_length=50, null=True, verbose_name='Полное имя')),
                ('description', models.TextField(help_text='Напишите описание отзыва о данной услуге.', verbose_name='Описание')),
                ('description_ru', models.TextField(help_text='Напишите описание отзыва о данной услуге.', null=True, verbose_name='Описание')),
                ('description_en', models.TextField(help_text='Напишите описание отзыва о данной услуге.', null=True, verbose_name='Описание')),
                ('description_uz', models.TextField(help_text='Напишите описание отзыва о данной услуге.', null=True, verbose_name='Описание')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/')),
                ('is_active', models.BooleanField(default=False, help_text="Установите значение 'True', чтобы активировать этот отзыв.", verbose_name='Активен')),
                ('service', models.ForeignKey(help_text='Укажите услугу, к которой относится этот отзыв.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='projects.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.blog')),
            ],
        ),
    ]
