# Generated by Django 4.2.3 on 2024-04-24 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about_images/', verbose_name='Imageabout')),
            ],
        ),
        migrations.CreateModel(
            name='Blog_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog_images/', verbose_name='Imageblog')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_blog', to='projects.blog')),
            ],
        ),
        migrations.RemoveField(
            model_name='about',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='about',
            name='title',
        ),
        migrations.RemoveField(
            model_name='about',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='about',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='about',
            name='title_uz',
        ),
        migrations.RemoveField(
            model_name='about',
            name='updated_at',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='about_image',
            name='about',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_about', to='projects.about'),
        ),
    ]
