# Generated by Django 4.2.3 on 2024-05-26 18:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_remove_blog_address_remove_blog_address_en_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="description_en",
        ),
        migrations.RemoveField(
            model_name="review",
            name="description_ru",
        ),
        migrations.RemoveField(
            model_name="review",
            name="description_uz",
        ),
        migrations.RemoveField(
            model_name="review",
            name="name_en",
        ),
        migrations.RemoveField(
            model_name="review",
            name="name_ru",
        ),
        migrations.RemoveField(
            model_name="review",
            name="name_uz",
        ),
    ]
