# Generated by Django 4.2.3 on 2024-05-02 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_remove_review_image_review_delete_review_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Загрузите изображение.",
                        upload_to="review_images",
                        verbose_name="Изображение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение",
                "verbose_name_plural": "Изображения",
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Введите ваш номер телефона.",
                        max_length=20,
                        verbose_name="Номер телефона",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Введите заголовок.",
                        max_length=255,
                        verbose_name="Заголовок",
                    ),
                ),
                (
                    "index_code",
                    models.CharField(
                        help_text="Введите индекс.",
                        max_length=20,
                        verbose_name="Индекс",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите ваше имя.",
                        max_length=100,
                        verbose_name="Имя",
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        help_text="Введите ваше имя.",
                        max_length=100,
                        null=True,
                        verbose_name="Имя",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        help_text="Введите ваше имя.",
                        max_length=100,
                        null=True,
                        verbose_name="Имя",
                    ),
                ),
                (
                    "name_uz",
                    models.CharField(
                        help_text="Введите ваше имя.",
                        max_length=100,
                        null=True,
                        verbose_name="Имя",
                    ),
                ),
                (
                    "surname",
                    models.CharField(
                        help_text="Введите вашу фамилию.",
                        max_length=100,
                        verbose_name="Фамилия",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        help_text="Введите ваш адрес.",
                        max_length=255,
                        verbose_name="Адрес",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        help_text="Введите любые дополнительные заметки.",
                        verbose_name="Заметка",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Напишите описание отзыва о данной услуге.",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(
                        help_text="Напишите описание отзыва о данной услуге.",
                        null=True,
                        verbose_name="Описание",
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        help_text="Напишите описание отзыва о данной услуге.",
                        null=True,
                        verbose_name="Описание",
                    ),
                ),
                (
                    "description_uz",
                    models.TextField(
                        help_text="Напишите описание отзыва о данной услуге.",
                        null=True,
                        verbose_name="Описание",
                    ),
                ),
                (
                    "mail",
                    models.EmailField(
                        help_text="Введите ваш адрес электронной почты.",
                        max_length=255,
                        verbose_name="Электронная почта",
                    ),
                ),
                (
                    "images",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Выберите изображения для этого отзыва.",
                        related_name="reviews",
                        to="projects.image",
                        verbose_name="Изображения",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        help_text="Укажите услугу, к которой относится этот отзыв.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="projects.service",
                        verbose_name="Услуга",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
            },
        ),
    ]
