# Generated by Django 4.2.3 on 2024-05-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0005_alter_review_address_alter_review_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="images",
            field=models.ManyToManyField(
                blank=True,
                help_text="Выберите изображения для этого отзыва.",
                related_name="reviews",
                to="projects.image",
                verbose_name="Изображения",
            ),
        ),
    ]
