# Generated by Django 4.2.3 on 2024-05-14 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_image_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'About', 'verbose_name_plural': 'About'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Online Application', 'verbose_name_plural': 'Online Application'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Service'},
        ),
        migrations.RemoveField(
            model_name='blog',
            name='contact_information',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='contact_information_en',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='contact_information_ru',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='contact_information_uz',
        ),
    ]
